### ISSUE TITLE
Need better way to find unknown time zones

### ISSUE THREAD

**Issue by DanielSantoro** [andytlr/homeslice#14]
Hey there!

Your tool seems neat - very handy for global companies :) The only problem is that I don't know what cities share what time zones across the world - it would be great if you either had options like 
- UTC -5
- UTC -4
- UTC -3
- etc.

So I could add those.

Alternatively, it would be nice to add a search bar where you entered the city and the time zone came up for you. This would allow the headers in each column to reflect the actual location - for example, I need to know the times in:
- San Diego, California
- Cincinnati, Ohio
- London, England
- Cape Town, South Africa

And would like those cities to show at the top of each column. Maybe even allow me to add nicknames to each column so I know which company is what at a glance :)

**Comment by andytlr** [comment]
> The only problem is that I don't know what cities share what time zones across the world - it would be great if you either had options like
> 
> UTC -5
> UTC -4
> UTC -3

I tried to solve this problem by showing the current time in the list of cities. In the screenshot below you can see that US Pacific, SFO and LA are essentially duplications because the time is the same.

![shot_2014-09-02_07-43-22](https://cloud.githubusercontent.com/assets/475255/4112246/09dd0486-3221-11e4-8f80-6e648264bba1.png)

> Alternatively, it would be nice to add a search bar where you entered the city and the time zone came up for you.

I would like to do something like this. I'm using [Moment Timezone](http://momentjs.com/timezone/) for the timezone data. At the moment I'm using a small subset of this list because the full list is a monster. But I can see how anyone would want _their_ city in the header, not some other city in the same timezone.

The other thing I considered was using country names for countries that reside entirely in one timezone. But this seems somewhat fragile. I think relying on the list of cities from Moment Timezone is the safest way to be accurate. But as you can see in #13, not every city is there which is also an issue.
